language: node_js
node_js:
- lts/*
cache: yarn
script:
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: cUl2qklAOcQuMkcvRGgMC4GLZ58V4RVNh8c31Qyb49j5R4DhJQx52UY76rbqWUCe44vkRBF/vfBJtZQuMj1XHtjydrHsnPxS/lXAsZoe6KaJ5MFmBHmQIhiFG60DXlf0HVpl88VckHqWP8+YJ4Zg7FZn3itcSafc8teN9mP4J00+XJRKEFGqGyg4lqk3nB9kzOIPbIGJfg0kUvfJn6mWvW92YeFVOK7tdZjeSMlA500GOkdQo9JNAOCFChRr4uKFSsSHbmmx0Etw5+7va93mv2fTLGE3nV+xzR4j6vajHliEqg3f1DrIlC5yRomxGYswpG9+lPog8FuP+2OpVdGlpjSQthqS+8vnLvH9Xe9OymekVGBN5BieKME8TPA6ibqZYDGktiS1f2lybNHwxVt7IIiqt+aC/KSd6G5bm8BXUibSEPdDTfmfgrgFlyK29gi4bl63jH3wGFmM5llPmGF7jlW3oisW0oQrnXi/8UTolJuvIRTRDwdQjfMD8j5Cpfqmk+nTNIX7Sb48+KfpfSafCuMp9QoLB2YQcUGEZYwD8UbOxxu0yRpF4O2lEy6KJfBGYRs14jGKLr8X2kLfz8xs5y9X+RaBWjmRFAfbRpbrrbRIUkr/yw4hhgkuO+SFAmzWsly952Vy9rh3VH6CupPDniqIt5us3jin35d3T6huRdI=
  app: fujit
  on:
    repo: vicente-palomero/fujit
  skip_cleanup: 'true'
